miniblog/blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('logout/', views.user_logout, name='logout'),
    path('add/post/', views.add_post, name='add_post'),
    path('post-detail/<int:pk>/', views.post_detail, name='detail'),
    path('post-edit/<int:pk>/', views.post_edit, name='update'),
    path('post-delete/<int:pk>/', views.post_delete, name='delete'),
    path('search', views.search, name='search'),
]

miniblog/miniblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

miniblog/blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    desc = models.TextField()


class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    desc = models.TextField()

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comments')

miniblog/blog/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,UsernameField
from django.contrib.auth.models import User
from django import forms
from .models import Contact,Post,Comment


class UserForm(UserCreationForm):
    password2 = forms.CharField(label='Re-Enter Password', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['first_name','last_name','username']
        widgets = {
            'first_name':forms.TextInput(attrs={'required':True,'autofocus':True}),
            'last_name':forms.TextInput(attrs={'required':True,'autofocus':True}),
            # 'last_name':forms.CharField(required=True),
            # 'name':forms.CharField(required=True),
        }

class ContactForm(forms.ModelForm):
    desc = forms.CharField(min_length=5, max_length=100, label='Your Message', widget=forms.Textarea(attrs={'rows':"4",}))
    class Meta:
        model = Contact
        fields = '__all__'
        
class UserProfileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ['first_name','last_name','username']
        labels = {'email':'Email'}


class AdminProfileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = '__all__'
        labels = {'email':'Email'}


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # exclude = ('author',)
        fields = ['title','desc']
        labels = {
            'desc':'Text',
        }

class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'cols':2,'rows':2}))
    class Meta:
        model = Comment
        fields = ['text']

miniblog/blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from .models import Post,Comment
from .forms import UserForm,ContactForm,AdminProfileForm,UserProfileForm,PostForm,CommentForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User,Group
from django.contrib.auth.decorators import login_required 

# Create your views here.
def home(request):
    post = Post.objects.all()
    comment = Comment.objects.all()
    return render(request,'blog/home.html',{'posts':post,'home':'active bb','hsr':'Recent Posts','comments':comment})

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST or None)
        if form.is_valid():
            form.save()
            form = ContactForm()
    else:
        form = ContactForm()
    return render(request,'blog/contact.html',{'form':form,'contact':'active bb'})

def about(request):
    return render(request,'blog/about.html',{'about':'active bb'})

def user_signup(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = UserForm(request.POST or None)
            if form.is_valid():
                user = form.save()
                group = Group.objects.get(name='Member')
                user.groups.add(group)
                messages.success(request,'Accont Created Successfully. log in with username and password')
        else:
            form = UserForm()
        return render(request,'blog/signup.html',{'form':form,'signup':'active bb'})
    else:
        return HttpResponseRedirect('/dashboard/')

def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request,user)
                    return render(request,'blog/dashboard.html',{'dashboard':'active bb'})
        else:
            form = AuthenticationForm()
        return render(request,'blog/login.html',{'form':form,'login':'active bb'})
    else:
        return HttpResponseRedirect('/dashboard/')

@login_required
def user_dashboard(request):
    if request.user.is_authenticated:
        if request.user.has_perm('blog.add_post'):
            posts = Post.objects.filter(author=request.user)
            gps = request.user.groups.all()
            if request.method == 'POST':
                if request.user.is_superuser:
                    form = AdminProfileForm(request.POST, instance=request.user)
                else:
                    
                    form = UserProfileForm(request.POST, instance=request.user)
                if form.is_valid():
                    form.save()
                    return HttpResponseRedirect('/dashboard/')
            else:
                if request.user.is_superuser:
                    form = AdminProfileForm(instance=request.user)
                else:
                    form = UserProfileForm(instance=request.user)
            return render(request,'blog/dashboard.html',{'form':form,'dashboard':'active bb','post':posts,'gps':gps})
        else:
            return render(request,'blog/dashboard.html') 
    else:
        return HttpResponseRedirect('/login/')

@login_required
def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
        return HttpResponseRedirect('/login/')
    else:
        return HttpResponseRedirect('/login/')

@login_required
def add_post(request):
    if request.user.is_authenticated:
        if request.user.has_perm('blog.add_post'):
            if request.method == 'POST':
                form = PostForm(request.POST or None)
                if form.is_valid():
                    form.instance.author = request.user
                    form.save()
                    return HttpResponseRedirect('/dashboard/')
            else:
                form = PostForm()
            return render(request,'blog/add_post.html',{'form':form,'heading':'New Post','bn':'Post','ttl':'Add'})


def post_detail(request, pk):
    # cmt = Comment.objects.filter(post=pk)
    posts = Post.objects.get(id=pk)
    cmt = posts.comments.all()
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = CommentForm(request.POST or None)
            if form.is_valid():
                comment= form.save(commit=False)
                comment.post = posts
                comment.author = request.user
                comment.save() 
                return redirect(to='blog:detail', pk=pk)
        else:
            form = CommentForm()
    else:
        form = {}
    return render(request,'blog/detail.html',{'posts':posts,'form':form,'cmt':cmt})

@login_required
def post_edit(request,pk):
    post = Post.objects.get(id=pk)
    form = PostForm(request.POST or None, instance=post)
    if request.user == post.author:
        if request.method == 'POST':
                form.save()
                return HttpResponseRedirect('/')
        else:
            return render(request,'blog/add_post.html',{'forms':form,'heading':'Edit Post','bn':'Save','ttl':'Edit','post':post})
    else:
        return HttpResponseRedirect('/')


@login_required
def post_delete(request,pk):
    if request.user.is_authenticated and request.user.is_superuser:
        post = Post.objects.get(id=pk)
        post.delete()
        return HttpResponseRedirect('/')


def search(request):
    if request.method == 'GET':
        data = request.GET.get('name')
        if len(data) != 0:
            posts = Post.objects.filter(desc__contains=data).all()
            count = posts.count()
            return render(request,'blog/home.html',{'posts':posts,'home':'active bb','hsr':'Searched Results','count':count})
        else:
            return HttpResponseRedirect('/')

miniblog/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block title %}About{% endblock title %}
{% block body %}
<div class="container w-75 mt-5">
    <h1 class='text-center mb-4 text-warning'>About Us</h1>
    <p class='mx-4 px-3 mt-4'>
        What is Lorem Ipsum?
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Why do we use it?
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).


    </p>
</div>
{% endblock body %}

miniblog/blog/templates/blog/add_post.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ttl}}{% endblock title %}
{% block body %}

<div class="container w-75 mt-4">
    <div class='mb-5'>
        <h1 class='bb' style='display:inline'>{{heading}}</h1>
    </div>
    <form action="{% if forms %}{% url 'blog:update' post.id %}{% else %} {% url 'blog:add_post' %} {% endif %}" method="post">
        {% csrf_token %}
        {% if forms %}
        {{forms|crispy}}
        {% else %}
        {{form|crispy}}
        {% endif %}
        <input type="submit" value="{{bn}}" class='btn btn-outline-warning mt-3'>
        <a href="{% url 'blog:dashboard' %}" class='btn btn-outline-success mt-3 ms-2'>Go back</a>
    </form>
</div>


{% endblock body %}

miniblog/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Charis+SIL:ital@1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/master.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body class=''>
    <div class="container-fluid">
        {% include 'blog/navbar.html' %}
    </div>
    <div class="container">
        {% block msg %}{% endblock msg %}
    </div>
    <div class="row">
        {% block side %}
        {% endblock side %}
        
        {% block content %}
        {% endblock content %}
    </div>
    <div>
        {% block body %}
        
        {% endblock body %}
    </div>
</body>
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<script src="{% static 'blog/js/jQuery.js' %}"></script>
<script src="{% static 'blog/js/popper.js' %}"></script>
</html>

miniblog/blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Contact{% endblock title %}

{% block body %}

<div class="container w-50 mt-5">
    <h1 class='text-center text-warning'>Contact Us</h1>
    <form action="{% url 'blog:contact' %}" method="post" class='mt-3' novalidate>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Submit" class='btn btn-outline-warning mt-3'>
    </form>
</div>

{% endblock body %}

miniblog/blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock title %}



{% block side %}
<div class="col-sm-4">
    <div class='ms-3 mt-2'>
        <h1 class='text-center bb' style='display:inline;'>Dashboard</h1>
    </div>
    <div class="container mt-3 bbr">
        <h3 class='text-center mb-3 pt-4 text-warning'>Profile</h3>
        <div class='text-center'>
            <img src="{% static 'blog/images/no_profile.png' %}" alt="" class='rounded-circle w-25 text-center'>
        </div>
        <h4 class='text-center'>
            {{request.user.first_name}} {{request.user.last_name}}
        </h4>
        {% if request.user.is_superuser %}
        <p class='text-center text-danger'>Admin</p>
        {% else %}
        {% for group in gps %}
        <p class='text-center text-danger'>{{group.name}}</p>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock side %}


{% block content %}
<div class="col-sm-8">
    <div class="container">
        {% block msg %}
        {% endblock msg %}
        <div>
            <h1 class='bbt mt-4'>Your Posts</h1>
            <div>
                {% if perms.blog.add_post %}
                <a href="{% url 'blog:add_post' %}" class='btn btn-success my-1'>Add Post</a>
                {% endif %}
            </div>
            {% if post %}
            <table class="table table-dark table-striped table-hover">
                <thead class='bb'>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col" class='text-center'>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pt in post %}
                    
                    <tr>
                        <th scope="row">{{pt.id}}</th>
                        <td>{{pt.title|truncatechars:17}}</td>
                        <td>{{pt.desc|truncatechars:20}}</td>
                        <td class='text-center'>
                            <a href="{% url 'blog:update' pt.id %}" class='btn btn-warning  btn-sm my-2'>Edit</a>
                            <a href="{% url 'blog:detail' pt.id %}" class='btn btn-success btn-sm my-2 mx-2'>View Post</a>
                            {% if request.user.is_superuser %}
                            <a href="{% url 'blog:delete' pt.id %}" class='btn btn-danger btn-sm my-2 '>Delete</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <h2 class='mt-5 ms-5 pt-5 ps-5'>You haven't posted anyting.</h2>
                    {% endif %}
                </tbody>
            </table>
            
            
        </div>
    </div>
</div>
{% endblock content %}

miniblog/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}{% if posts %}{{posts.title}}{% endif %}{% endblock title %}
{% block body %}

<div class="container mx-5 px-5 mt-5">
    <h3>{{posts.title}}</h3>
    <p class='mt-3 pt-5 w-75'>{{posts.desc}}</p>

</div>

<hr class='container mt-5'>
{% if request.user.is_authenticated %}
<div class='ms-5 w-25'>
    <h3> Comment:</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Comment" class='btn btn-sm btn-warning mt-2'>
    </form>
</div>
{% else %}
<h3 class='ms-5'>Please login to comment <small><a href="{% url 'blog:login' %}" class='text-decoration-none h5'>Login >></a></small></h3>
{% endif %}

<div class=" ms-5 my-2">
    <h4 class='border-bottom w-50 text-warning'>Comments</h4>
    {% if cmt %}
    {% for comment in cmt %}
    <div class='cmb'>
        <h3><i class="fa-solid fa-user fa-xs"></i> {{comment.author}}</h3>
        <p>{{comment.text}}</p>
        {% endfor %}
    </div>
        {% else %}
        <h4>No Comments Yet</h4>
        {% endif %}
</div>
{% endblock body %}

miniblog/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% block title %}Home{% endblock title %}
{% block body %}
<div class="col-sm-10">
    <div class="">
        <h3 class='ms-5 mt-4 bbt mb-4 w-25 '>{{hsr}} {{count}}</h3>
    </div>
    {% for post in posts %}
    <div class="container ms-5 py-5 px-5 w-100 bbr mb-3">
        <h2 class=''>
            <a href="{% url 'blog:detail' post.id %}" class='text-decoration-none tc'>
                {{post.title}}
            </a>
        </h2>
        <p class='w-50'>
            {{post.desc|truncatewords:20}}
        </p>
        <small class='text-warning'>Comments : <spanc class='text-info'>{{post.comments.count}}</span></small>
    </div>
    {% endfor %}
</div>
{% endblock body %}

miniblog/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock title %}

{% block body %}
<div class="container w-50 mt-5">
    <h1 class='mt-5'>Login</h1>
    <form action="{% url 'blog:login' %}" method="post" class='mt-5' novalidate>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Login" class='btn btn-outline-warning mt-3'>
    </form>
</div>

{% endblock body %}

miniblog/blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">myBlog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item ms-5">
            <a class="nav-link {{home}}" aria-current="page" href="{% url 'blog:home' %}">Home</a>
          </li>
          <li class="nav-item ms-5">
            <a class="nav-link {{about}} " href="{% url 'blog:about' %}">About</a>
          </li>
          <li class="nav-item ms-5">
            <a class="nav-link {{contact}}" href="{% url 'blog:contact' %}">Contact</a>
          </li>
          {% if not request.user.is_authenticated %}
          <li class="nav-item ms-5">
            <a class="nav-link {{signup}}" href="{% url 'blog:signup' %}">Sign Up</a>
          </li>
          <li class="nav-item ms-5">
            <a class="nav-link {{login}}" href="{% url 'blog:login' %}">Log In</a>
          </li>
          {% else %}
          <li class="nav-item ms-5">
            <a class="nav-link {{dashboard}}" href="{% url 'blog:dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item ms-5">
            <a class="nav-link" href="{% url 'blog:logout' %}">logout</a>
          </li>

          {% endif %}
          
        </ul>
        {% if posts %}
        <form action='{% url "blog:search" %}' method='get' class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name=name>
          <button class="btn btn-outline-warning" type="submit">Search</button>
        </form>
        {% endif %}
      </div>
    </div>
  </nav>

miniblog/blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Signup{% endblock title %}
{% block msg %}{% if messages %}
{% for message in messages %}
<span {% if message.tags %} class='text-{{message.tags}} ms-3'{% endif %}>{{message}}</span>
{% endfor %}
{% endif %}{% endblock msg %}
{% block body %}
<div class="container mt-4 w-50">
    <div class='my-2 mb-3'>
        <h1 class='bb' style='display:inline'>Register</h1>
    </div>
    <form action="{% url 'blog:signup' %}" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Register" class='btn btn-outline-warning mt-3'>
    </form>
</div>
{% endblock body %}